// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // We handle callback URLs explicitly via handleAuthCallbackUrl for both
    // web (/auth/callback) and native deep links (pastelly://auth/callback).
    // Disabling automatic detection prevents Strict-Mode double exchanges
    // and races with our handler.
    detectSessionInUrl: false,
  },
});
